name: Model Tests

on:
  push:
    paths:
      - 'model/**'
      - 'tests/model/**'
  pull_request:
    paths:
      - 'model/**'
      - 'tests/model/**'

jobs:
  test-model:
    name: Run Model Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: model

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Cache virtualenv
        uses: actions/cache@v3
        with:
          path: model/venv
          key: ${{ runner.os }}-venv-${{ hashFiles('model/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-

      - name: Set up virtualenv
        run: |
          python -m venv venv

      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run model tests
        run: |
          source venv/bin/activate
          pytest -n auto
